baseURL: http://citizenlabs.org/
languageCode: en-us
title: Citizen Labs
theme: hugo-fresh
MetaDataFormat: yaml
googleAnalytics: UA-115392197-1
#Disables warningss
disableKinds:
 -taxonomy
 -taxonomyTerm


params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  defaultKeywords: ["citizen labs", "open data", "grand rapids", "open source", "open budget"]
  description: Empowering citizens to improve their communities and local government.
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/CL_Logo-04-orange.png
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Let's Make Our Community Better Together
    # Hero subtitle (optional)
    subtitle:
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "join"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - heart
    - grwebdev
    - pyladies
    - wmrn
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Join Us
    url: /join
  - title: Our Work
    url: /our_work
  - title: About
    sublinks:
    - title: Code of Conduct
      url: /conduct
    - title: Sponsors
      url: /about/sponsor
    - title: Our Team
      url: /about/team
  - title: News
    url: /post
  - title: Contact
    url: /#contact
    button: true
  section1:
    title: How Do We Do It?
    subtitle: the tools in our toolbox
    tiles:
    - title: Open Data
      icon: mouse-globe
      text: We create or discover data, then put it to work.
      url: /open_data
      buttonText: Learn more
    - title: Open Source Software
      icon: laptop-cloud
      text: Commmon problems often allow for common solutions.
      url: /open_source
      buttonText: Learn more
    - title: Empowering People
      icon: plug-cloud
      text: We live, work, and improve our communities.
      url: /people
      buttonText: Learn more
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Our Civic Partners Love Us!
    subtitle:
    clients:
    - name: Rosalyn Bliss
      quote: THANK YOU so much for all of your help as we push to improve our digital city.
      job: Mayor of Grand Rapids
      img: 1
    - name:  Scott Buhrer
      quote: The open budget website promotes a deeper understanding of the City budget... for our residents, officials and other stakeholders. I am grateful to the team for assisting us with set-up and maintenance of the site.
      job: CFO, City of Grand Rapids
      img: 3
    - name: Ruth Kelly
      quote: We appreciate all of the hard work of the team and look forward to more solutions and opportunities as you engage with the city. We appreciate your having completed the task on time. The timing was excellent!
      job: Commissioner, City of Grand Rapids
      img: 4
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: CL_Logo.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/citizenlabsgr
      # Icons are from Font Awesome
      icon:
    - link: https://www.meetup.com/Citizen-Labs/
      icon: meetup
    - link: https://www.facebook.com/citizenlabs
      icon: facebook
    - link: https://twitter.com/citizen_labs
      icon: twitter
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /post
        - text: Tech articles
          link: /blog/second
